#!/bin/bash -e

TARGET_PREFIX=${1:-release}
TARGET_BASE=$TARGET_PREFIX-`date +%Y%m%d`
TARGET_REVISION=$((`git ls-remote --tags --heads origin | awk "/tags\/$TARGET_BASE-(.*)/ { print $1 }" | awk -F'-' '{print $3}' | sort -nr | head -n 1` + 1))
TARGET_BRANCH=$TARGET_BASE-$TARGET_REVISION
git tag $TARGET_BRANCH
git push origin $TARGET_BRANCH
echo "tagging complete under tag $TARGET_BRANCH"
