#!/bin/sh

if [ "$1" = "recent" ]; then
	ADDITONAL_OPTIONS="-mmin -240"
else
	ADDITONAL_OPTIONS=""
fi

find . $ADDITONAL_OPTIONS -type f -prune -name "*.php" -print0 | xargs -0 -n1 -P10 php -l | grep -v 'No syntax errors'

if [ "$?" -eq "0" ]; then
  exit 1
else
  exit 0
fi
