#!/bin/sh

[[ "$1" = "recent" ]] && ADDITONAL_OPTIONS="-mmin -240"

find . $ADDITONAL_OPTIONS -name "*.rb" -print0 | xargs -0 -n1 -P10 ruby -c | grep -v 'Syntax OK'

if [ "$?" -eq "0" ]; then
  exit 1
else
  exit 0
fi
